services:
  nginx:
    image: dockersfc/soundcollect-dash-nginx:${IMAGE_TAG}
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  frontend:
    image: dockersfc/soundcollect-dash-frontend:${IMAGE_TAG}
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:1.5.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER=${DOCKERHUB_USERNAME}
      - REPO_PASS=${DOCKERHUB_PASSWORD}
